import { expect, test, describe } from 'vitest'
import * as utils from "../util"

describe("isScaleVariant", () => {
	test("foo.png is not a scale variant", () => {
		expect(utils.isScaleVariant("foo.png")).toBe(false)
	})

	test("foo@2x.png is a scale variant", () => {
		expect(utils.isScaleVariant("foo@2x.png")).toBe(true)
	})
})

describe("uniqNames", () => {
	test("given paths like ['foo.jpg', 'foo.png', 'foo.svg'], return ['foo.png']", () => {
		let input = new Set(["foo.jpg", "foo.png", "foo.svg"])
		expect(utils.uniqNames(input)).toEqual(new Set(["foo.png"]))
	})
})

describe("isBaseVariant", () => {
	test("foo@2x.png is a base variant of foo.png", () => {
		expect(utils.isBaseVariant("foo.png", "foo@2x.png")).toBe(true)
	})

	test("foo@2x.png is not a base variant of bar.png", () => {
		expect(utils.isBaseVariant("bar.png", "foo@2x.png")).toBe(false)
	})
})

describe("codegen", () => {
	test("generates code", () => {
		let result = utils.codegen("src/_tests/fixtures/smile.png", [
			"src/_tests/fixtures/smile@2x.png",
		])
		let expected = `// generated by srcset-codegen
import src from "./smile.png";
import src2x from "./smile@2x.png";

const width = 107;
const height = 107;
const srcSet = \`\${src2x} 2x\`;
export default { src, width, height, srcSet };
`

		expect(result).toEqual(expected)
	})
	test("generates more variants", () => {
		let result = utils.codegen("src/_tests/fixtures/smile.png", [
			"src/_tests/fixtures/smile@2x.png",
			"src/_tests/fixtures/smile@3x.png",
		])
		let expected = `// generated by srcset-codegen
import src from "./smile.png";
import src2x from "./smile@2x.png";
import src3x from "./smile@3x.png";

const width = 107;
const height = 107;
const srcSet = \`\${src2x} 2x, \${src3x} 3x\`;
export default { src, width, height, srcSet };
`

		expect(result).toEqual(expected)
	})

	test("it doesn't generate a srcset if there are no variants", () => {
		let result = utils.codegen("src/_tests/fixtures/smile.png", [])
		let expected = `// generated by srcset-codegen
import src from "./smile.png";

const width = 107;
const height = 107;
export default { src, width, height };
`

		expect(result).toEqual(expected)
	})
})
