name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - run: pnpm i
      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - run: pnpm i
      - run: pnpm test
